source 'https://rubygems.org'
gem 'jekyll'
gem 'webrick', '~> 1.7'
gem 'kramdown-math-katex', '~> 1.0'
gem 'liquid-c'

group :jekyll_plugins do
    gem 'jekyll-toc'
    gem 'jekyll-postfiles'
    gem 'jekyll-sass-converter'
    gem 'jekyll-compose'
    gem 'jemoji'
    gem 'algolia'
    gem 'jekyll-default-layout'
    gem 'jekyll-archives'
    gem 'jekyll-feed'
    gem 'jekyll-include-cache'
    gem 'jekyll-remote-theme'
    gem 'jekyll-seo-tag'
    gem 'jekyll-sitemap'
end